name: 'Hostloc Auto RSS'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 0/6 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
    - name: 'Install lxml' 
      run: python -m pip install --upgrade lxml
    - name: 'Install torequests'
      run: python -m pip install --upgrade torequests     
    - name: 'Install js2py'
      run: python -m pip install --upgrade js2py
    - name: 'Post push'
      env:
          POST_URL: ${{ secrets.POST_URL }}
          TG_ID: ${{ secrets.TG_ID }}
      run: python hostloc_tg.py
